### PR TITLE
Remove Tweener import to make compatible with 3.38

### PR DESCRIPTION
**Pull request by TpmKranz**
This should be a more forward-looking fix than #23, provided I got the right replacement functions. So far it's working for me, although I'm not sure what I should be looking for to verify the changes don't break anything.

### CODE REVIEW

**Comment by brsvh** [comment]
It works fine for me. (ArchLinux, 3.38.1)

**Comment by moshiur-raj** [comment]
Works for me too.

**Comment by Elvith** [comment]
Any news on this front? What are we waiting for? Is there something we can do?

**Comment by poehlerj** [comment]
I'm sorry, I was unable to find the time over the last couple of months. I just upgraded my own system to Gnome 3.38 and now merge this PR and have a look at the rest of outstanding changes. After that I will release an updated Version on extensions.gnome.org

**Pull request merged**
